[package]
name = "ir"
description = "Intermediate representation for weakc"
version = "0.1.0"
edition = "2021"

[dependencies]
bump = { path = "../bump" }
parse = { path = "../parse" }
semant = { path = "../semant" }
